CREATE TABLE Books(
   ID uniqueidentifier NOT NULL  DEFAULT newid() PRIMARY KEY
  ,Total_Count INTEGER	NOT NULL
  ,Cuurent_Count INTEGER	NOT NULL
  ,Title     NVARCHAR(100) NOT NULL 
  ,Author    NVARCHAR(100)
  ,Genre     NVARCHAR(100)
  ,SubGenre  NVARCHAR(100)
  ,Height    INTEGER 
  ,Publisher NVARCHAR(100)
);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Fundamentals of Wavelets','Goswami, Jaideva','tech','signal_processing',228,'Wiley');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Data Smart','Foreman, John','tech','data_science',235,'Wiley');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'God Created the Integers','Hawking, Stephen','tech','mathematics',197,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Superfreakonomics','Dubner, Stephen','science','economics',179,'HarperCollins');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Orientalism','Said, Edward','nonfiction','history',197,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Nature of Statistical Learning Theory, The','Vapnik, Vladimir','tech','data_science',230,'Springer');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Integration of the Indian States','Menon, V P','nonfiction','history',217,'Orient Blackswan');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Drunkard''s Walk, The','Mlodinow, Leonard','science','mathematics',197,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Image Processing & Mathematical Morphology','Shih, Frank','tech','signal_processing',241,'CRC');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'How to Think Like Sherlock Holmes','Konnikova, Maria','nonfiction','psychology',240,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Data Scientists at Work','Sebastian Gutierrez','tech','data_science',230,'Apress');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Slaughterhouse Five','Vonnegut, Kurt','fiction','classic',198,'Random House');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Birth of a Theorem','Villani, Cedric','science','mathematics',234,'Bodley Head');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Structure & Interpretation of Computer Programs','Sussman, Gerald','tech','computer_science',240,'MIT Press');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Age of Wrath, The','Eraly, Abraham','nonfiction','history',238,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Trial, The','Kafka, Frank','fiction','classic',198,'Random House');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Statistical Decision Theory''','Pratt, John','tech','data_science',236,'MIT Press');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Data Mining Handbook','Nisbet, Robert','tech','data_science',242,'Apress');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'New Machiavelli, The','Wells, H. G.','fiction','novel',180,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Physics & Philosophy','Heisenberg, Werner','philosophy','science',197,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Making Software','Oram, Andy','tech','computer_science',232,'O''Reilly');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Analysis, Vol I','Tao, Terence','tech','mathematics',248,'HBA');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Machine Learning for Hackers','Conway, Drew','tech','data_science',233,'O''Reilly');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Signal and the Noise, The','Silver, Nate','tech','data_science',233,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Python for Data Analysis','McKinney, Wes','tech','data_science',233,'O''Reilly');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Introduction to Algorithms','Cormen, Thomas','tech','computer_science',234,'MIT Press');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Beautiful and the Damned, The','Deb, Siddhartha','nonfiction','history',198,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Outsider, The','Camus, Albert','fiction','classic',198,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Complete Sherlock Holmes, The - Vol I','Doyle, Arthur Conan','fiction','classic',176,'Random House');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Complete Sherlock Holmes, The - Vol II','Doyle, Arthur Conan','fiction','classic',176,'Random House');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Wealth of Nations, The','Smith, Adam','science','economics',175,'Random House');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Pillars of the Earth, The','Follett, Ken','fiction','novel',176,'Random House');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Mein Kampf','Hitler, Adolf','nonfiction','autobiography',212,'Rupa');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Tao of Physics, The','Capra, Fritjof','science','physics',179,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Surely You''re Joking Mr Feynman','Feynman, Richard','science','physics',198,'Random House');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Farewell to Arms, A','Hemingway, Ernest','fiction','classic',179,'Rupa');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Veteran, The','Forsyth, Frederick','fiction','novel',177,'Transworld');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'False Impressions','Archer, Jeffery','fiction','novel',177,'Pan');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Last Lecture, The','Pausch, Randy','nonfiction','autobiography',197,'Hyperion');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Return of the Primitive','Rand, Ayn','philosophy','objectivism',202,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Jurassic Park','Crichton, Michael','fiction','novel',174,'Random House');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Russian Journal, A','Steinbeck, John','nonfiction','history',196,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Tales of Mystery and Imagination','Poe, Edgar Allen','fiction','classic',172,'HarperCollins');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Freakonomics','Dubner, Stephen','science','economics',197,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Hidden Connections, The','Capra, Fritjof','science','physics',197,'HarperCollins');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Story of Philosophy, The','Durant, Will','philosophy','history',170,'Pocket');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Asami Asami','Deshpande, P L','fiction','novel',205,'Mauj');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Journal of a Novel','Steinbeck, John','fiction','classic',196,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Once There Was a War','Steinbeck, John','nonfiction','history',196,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Moon is Down, The','Steinbeck, John','fiction','classic',196,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Brethren, The','Grisham, John','fiction','novel',174,'Random House');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'In a Free State','Naipaul, V. S.','fiction','novel',196,'Rupa');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Catch 22','Heller, Joseph','fiction','classic',178,'Random House');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Complete Mastermind, The','BBC','nonfiction','trivia',178,'BBC');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Dylan on Dylan','Dylan, Bob','nonfiction','autobiography',197,'Random House');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Soft Computing & Intelligent Systems','Gupta, Madan','tech','data_science',242,'Elsevier');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Textbook of Economic Theory','Stonier, Alfred','tech','economics',242,'Pearson');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Econometric Analysis','Greene, W. H.','tech','economics',242,'Pearson');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Learning OpenCV','Bradsky, Gary','tech','signal_processing',232,'O''Reilly');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Data Structures Using C & C++','Tanenbaum, Andrew','tech','computer_science',235,'Prentice Hall');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Computer Vision, A Modern Approach','Forsyth, David','tech','signal_processing',255,'Pearson');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Principles of Communication Systems','Taub, Schilling','tech','signal_processing',240,'TMH');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Let Us C','Kanetkar, Yashwant','tech','computer_science',213,'Prentice Hall');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Amulet of Samarkand, The','Stroud, Jonathan','fiction','novel',179,'Random House');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Crime and Punishment','Dostoevsky, Fyodor','fiction','classic',180,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Angels & Demons','Brown, Dan','fiction','novel',178,'Random House');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Argumentative Indian, The','Sen, Amartya','nonfiction','history',209,'Picador');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Sea of Poppies','Ghosh, Amitav','fiction','novel',197,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Idea of Justice, The','Sen, Amartya','philosophy','economics',212,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Raisin in the Sun, A','Hansberry, Lorraine','fiction','novel',175,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'All the President''s Men','Woodward, Bob','nonfiction','history',177,'Random House');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Prisoner of Birth, A','Archer, Jeffery','fiction','novel',176,'Pan');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Scoop!','Nayar, Kuldip','nonfiction','history',216,'HarperCollins');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Ahe Manohar Tari','Deshpande, Sunita','nonfiction','autobiography',213,'Mauj');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Last Mughal, The','Dalrymple, William','nonfiction','history',199,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Social Choice & Welfare, Vol 39 No. 1','Various','tech','economics',235,'Springer');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Radiowaril Bhashane & Shrutika','Deshpande, P L','nonfiction','misc',213,'Mauj');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Gun Gayin Awadi','Deshpande, P L','nonfiction','misc',212,'Mauj');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Aghal Paghal','Deshpande, P L','nonfiction','misc',212,'Mauj');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Maqta-e-Ghalib','Garg, Sanjay','nonfiction','poetry',221,'Mauj');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Beyond Degrees',NULL,'philosophy','education',222,'HarperCollins');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Manasa','Kale, V P','nonfiction','misc',213,'Mauj');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'India from Midnight to Milennium','Tharoor, Shashi','nonfiction','history',198,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'World''s Greatest Trials, The',NULL,'nonfiction','history',210,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Great Indian Novel, The','Tharoor, Shashi','fiction','novel',198,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'O Jerusalem!','Lapierre, Dominique','nonfiction','history',217,'vikas');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'City of Joy, The','Lapierre, Dominique','fiction','novel',177,'vikas');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Freedom at Midnight','Lapierre, Dominique','nonfiction','history',167,'vikas');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Winter of Our Discontent, The','Steinbeck, John','fiction','classic',196,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'On Education','Russell, Bertrand','philosophy','education',203,'Routledge');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Free Will','Harris, Sam','nonfiction','psychology',203,'FreePress');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Bookless in Baghdad','Tharoor, Shashi','nonfiction','history',206,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Case of the Lame Canary, The','Gardner, Earle Stanley','fiction','novel',179,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Theory of Everything, The','Hawking, Stephen','science','physics',217,'Jaico');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'New Markets & Other Essays','Drucker, Peter','science','economics',176,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Electric Universe','Bodanis, David','science','physics',201,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Hunchback of Notre Dame, The','Hugo, Victor','fiction','classic',175,'Random House');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Burning Bright','Steinbeck, John','fiction','classic',175,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Age of Discontuinity, The','Drucker, Peter','nonfiction','economics',178,'Random House');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Doctor in the Nude','Gordon, Richard','fiction','novel',179,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Down and Out in Paris & London','Orwell, George','nonfiction','autobiography',179,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Identity & Violence','Sen, Amartya','philosophy','philosophy',219,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Beyond the Three Seas','Dalrymple, William','nonfiction','history',197,'Random House');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'World''s Greatest Short Stories, The',NULL,'fiction','classic',217,'Jaico');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Talking Straight','Iacoca, Lee','nonfiction','autobiography',175,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Maugham''s Collected Short Stories, Vol 3','Maugham, William S','fiction','classic',171,'Vintage');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Phantom of Manhattan, The','Forsyth, Frederick','fiction','classic',180,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Ashenden of The British Agent','Maugham, William S','fiction','classic',160,'Vintage');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Zen & The Art of Motorcycle Maintenance','Pirsig, Robert','philosophy','autobiography',172,'Vintage');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Great War for Civilization, The','Fisk, Robert','nonfiction','history',197,'HarperCollins');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'We the Living','Rand, Ayn','fiction','novel',178,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Artist and the Mathematician, The','Aczel, Amir','science','mathematics',186,'HighStakes');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'History of Western Philosophy','Russell, Bertrand','philosophy','philosophy',213,'Routledge');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Selected Short Stories',NULL,'fiction','classic',215,'Jaico');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Rationality & Freedom','Sen, Amartya','science','economics',213,'Springer');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Clash of Civilizations and Remaking of the World Order','Huntington, Samuel','nonfiction','history',228,'Simon&Schuster');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Uncommon Wisdom','Capra, Fritjof','nonfiction','anthology',197,'Fontana');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'One','Bach, Richard','nonfiction','autobiography',172,'Dell');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Karl Marx Biography',NULL,'nonfiction','autobiography',162,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'To Sir With Love','Braithwaite','fiction','classic',197,'Penguin');
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Half A Life','Naipaul, V S','fiction','novel',196,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Discovery of India, The','Nehru, Jawaharlal','nonfiction','history',230,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Apulki','Deshpande, P L','nonfiction','misc',211,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Unpopular Essays','Russell, Bertrand','philosophy','philosophy',198,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Deceiver, The','Forsyth, Frederick','fiction','novel',178,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Veil: Secret Wars of the CIA','Woodward, Bob','nonfiction','history',171,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Char Shabda','Deshpande, P L','nonfiction','misc',214,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Rosy is My Relative','Durrell, Gerald','fiction','novel',176,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Moon and Sixpence, The','Maugham, William S','fiction','classic',180,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Political Philosophers',NULL,'philosophy','politics',162,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Short History of the World, A','Wells, H G','nonfiction','history',197,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Trembling of a Leaf, The','Maugham, William S','fiction','novel',205,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Doctor on the Brain','Gordon, Richard','fiction','novel',204,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Simpsons & Their Mathematical Secrets','Singh, Simon','science','mathematics',233,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Pattern Classification','Duda, Hart','tech','data_science',241,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'From Beirut to Jerusalem','Friedman, Thomas','nonfiction','history',202,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Code Book, The','Singh, Simon','science','mathematics',197,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Age of the Warrior, The','Fisk, Robert','nonfiction','history',197,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Final Crisis',NULL,'fiction','comic',257,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Killing Joke, The',NULL,'fiction','comic',283,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Flashpoint',NULL,'fiction','comic',265,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Batman Earth One',NULL,'fiction','comic',265,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Crisis on Infinite Earths',NULL,'fiction','comic',258,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Numbers Behind Numb3rs, The','Devlin, Keith','science','mathematics',202,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Superman Earth One - 1',NULL,'fiction','comic',259,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Superman Earth One - 2',NULL,'fiction','comic',258,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Justice League: Throne of Atlantis',NULL,'fiction','comic',258,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Justice League: The Villain''s Journey',NULL,'fiction','comic',258,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Death of Superman, The',NULL,'fiction','comic',258,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'History of the DC Universe',NULL,'fiction','comic',258,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Batman: The Long Halloween',NULL,'fiction','comic',258,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Life in Letters, A','Steinbeck, John','nonfiction','autobiography',196,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Information, The','Gleick, James','science','mathematics',233,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Journal of Economics, vol 106 No 3',NULL,'science','economics',235,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Elements of Information Theory','Thomas, Joy','tech','signal_processing',229,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Power Electronics - Rashid','Rashid, Muhammad','tech','computer_science',235,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Power Electronics - Mohan','Mohan, Ned','tech','computer_science',237,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Neural Networks','Haykin, Simon','tech','data_science',240,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Grapes of Wrath, The','Steinbeck, John','fiction','classic',196,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Vyakti ani Valli','Deshpande, P L','nonfiction','misc',211,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Statistical Learning Theory','Vapnik, Vladimir','tech','data_science',228,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Empire of the Mughal - The Tainted Throne','Rutherford, Alex','nonfiction','history',180,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Empire of the Mughal - Brothers at War','Rutherford, Alex','nonfiction','history',180,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Empire of the Mughal - Ruler of the World','Rutherford, Alex','nonfiction','history',180,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Empire of the Mughal - The Serpent''s Tooth','Rutherford, Alex','nonfiction','history',180,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Empire of the Mughal - Raiders from the North','Rutherford, Alex','nonfiction','history',180,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Mossad','Baz-Zohar, Michael','nonfiction','history',236,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Jim Corbett Omnibus','Corbett, Jim','nonfiction','history',223,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'20000 Leagues Under the Sea','Verne, Jules','fiction','novel',190,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Batatyachi Chal','Deshpande P L','fiction','novel',200,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Hafasavnuk','Deshpande P L','fiction','novel',211,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Urlasurla','Deshpande P L','fiction','novel',211,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Pointers in C','Kanetkar, Yashwant','tech','computer_science',213,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Cathedral and the Bazaar, The','Raymond, Eric','tech','computer_science',217,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Design with OpAmps','Franco, Sergio','tech','computer_science',240,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Think Complexity','Downey, Allen','tech','data_science',230,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Devil''s Advocate, The','West, Morris','fiction','novel',178,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Ayn Rand Answers','Rand, Ayn','philosophy','objectivism',203,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Philosophy: Who Needs It','Rand, Ayn','philosophy','objectivism',171,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'World''s Great Thinkers, The',NULL,'science','physics',189,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Data Analysis with Open Source Tools','Janert, Phillip','tech','data_science',230,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Broca''s Brain','Sagan, Carl','science','physics',174,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Men of Mathematics','Bell, E T','science','mathematics',217,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Oxford book of Modern Science Writing','Dawkins, Richard','science','science',240,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Justice, Judiciary and Democracy','Ranjan, Sudhanshu','nonfiction','legal',224,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Arthashastra, The','Kautiyla','philosophy','philosophy',214,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'We the People','Palkhivala','philosophy','philosophy',216,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'We the Nation','Palkhivala','philosophy','philosophy',216,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Courtroom Genius, The','Sorabjee','nonfiction','autobiography',217,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Dongri to Dubai','Zaidi, Hussain','nonfiction','history',216,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'History of England, Foundation','Ackroyd, Peter','nonfiction','history',197,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'City of Djinns','Dalrymple, William','nonfiction','history',198,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'India''s Legal System','Nariman','nonfiction','legal',177,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'More Tears to Cry','Sassoon, Jean','fiction','novel',235,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Ropemaker, The','Dickinson, Peter','fiction','novel',196,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Angels & Demons','Brown, Dan','fiction','novel',170,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Judge, The',NULL,'fiction','novel',170,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Attorney, The',NULL,'fiction','novel',170,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Prince, The','Machiavelli','fiction','classic',173,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Eyeless in Gaza','Huxley, Aldous','fiction','novel',180,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Tales of Beedle the Bard','Rowling, J K','fiction','novel',184,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Girl with the Dragon Tattoo','Larsson, Steig','fiction','novel',179,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Girl who kicked the Hornet''s Nest','Larsson, Steig','fiction','novel',179,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Girl who played with Fire','Larsson, Steig','fiction','novel',179,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Batman Handbook',NULL,'fiction','comic',270,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Murphy''s Law',NULL,'philosophy','psychology',178,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Structure and Randomness','Tao, Terence','science','mathematics',252,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Image Processing with MATLAB','Eddins, Steve','tech','signal_processing',241,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Animal Farm','Orwell, George','fiction','classic',180,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Idiot, The','Dostoevsky, Fyodor','fiction','classic',197,NULL);
INSERT INTO Books(Total_Count,Cuurent_Count,Title,Author,Genre,SubGenre,Height,Publisher) VALUES (3,3,'Christmas Carol, A','Dickens, Charles','fiction','classic',196,NULL);